.PHONY: setup

setup:
	# ディレクトリの作成
	mkdir -p src/app/domain/models
	mkdir -p src/app/domain/repositories
	mkdir -p src/app/application/services
	mkdir -p src/app/infrastructure/repositories
	mkdir -p src/app/interfaces/routers
	mkdir -p src/app/interfaces/schemas

	# ファイルの作成
	touch src/main.py
	touch src/app/domain/models/__init__.py
	touch src/app/domain/models/user.py
	touch src/app/domain/repositories/__init__.py
	touch src/app/domain/repositories/user_repository.py
	touch src/app/application/services/__init__.py
	touch src/app/application/services/user_service.py
	touch src/app/infrastructure/repositories/__init__.py
	touch src/app/infrastructure/repositories/user_repository_impl.py
	touch src/app/interfaces/routers/__init__.py
	touch src/app/interfaces/routers/user_router.py
	touch src/app/interfaces/schemas/__init__.py
	touch src/app/interfaces/schemas/user_schema.py
